### ISSUE TITLE
Crashes on open

### ISSUE THREAD

**Issue by sheeepdev** [Bnyro/TranslateYou#30]
### Steps to reproduce

1. Open the app
2. See a white screen for half a second
3. App closes

### Expected behavior

App should open and work

### Actual behavior

App crashes

### Translate You version

1.5

### Android version

Android 12

### Other details

When installing, a play protect menu sometimes pops up but if you try to click it nothing happens and it just says that the app is installed (this happens for both versions, libre and normal) ![](https://i.imgur.com/sJ9645r.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Hmm, that's very unfortunate, I didn't experience something similar yet.
The easiest thing for me would be if you could somehow access the crash/error log, a guide for that can be found [here](https://forum.xda-developers.com/t/tutorial-how-to-logcat.1726238/).
The warning means that Google doesn't know the app because it's not published at the Google Play Store, which shouldn't hurt in fact :)

**Comment by sheeepdev** [comment]
> Hmm, that's very unfortunate, I didn't experience something similar yet. The easiest thing for me would be if you could somehow access the crash/error log, a guide for that can be found [here](https://forum.xda-developers.com/t/tutorial-how-to-logcat.1726238/). The warning means that Google doesn't know the app because it's not published at the Google Play Store, which shouldn't hurt in fact :)

I think this is the right error:

```
[ 10-10 16:05:03.170 12539:12539 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: com.bnyro.translate.nf, PID: 12539
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
	at g3.p.a(SourceFile:387)
	at a3.e.P(SourceFile:167)
	at d0.a.d(SourceFile:50)
	at d0.a.P(Unknown Source:8)
	at u.i0$a.Q(SourceFile:203)
	at d0.a.Q(SourceFile:58)
	at u.m2.Q(SourceFile:197)
	at d0.a.Q(SourceFile:58)
	at w.k0.a(Unknown Source:28)
	at u.j2.a(SourceFile:9)
	at u.i0.a(SourceFile:52)
	at u.i0.b(SourceFile:22)
	at a3.c$c.P(SourceFile:428)
	at d0.a.d(SourceFile:50)
	at d0.a.P(Unknown Source:8)
	at u.a2.Q(SourceFile:130)
	at d0.a.Q(SourceFile:58)
	at a1.y.Q(SourceFile:59)
	at d0.a.Q(SourceFile:58)
	at w.n.B(SourceFile:37)
	at androidx.activity.l.w(SourceFile:44)
	at w.i.O(SourceFile:131)
	at w.i.K(Unknown Source:13)
	at w.h0.m(SourceFile:18)
	at w.x1.a(SourceFile:45)
	at w.i$b.a(SourceFile:10)
	at w.h0.j(Unknown Source:12)
	at a1.v.c(SourceFile:110)
	at a1.v$b.n0(SourceFile:138)
	at u.c2.W(SourceFile:50)
	at a1.g0.e(SourceFile:40)
	at a1.w$a.e(SourceFile:9)
	at c1.b0$b$a.B(SourceFile:105)
	at f0.h$a.a(SourceFile:64)
	at f0.b0.B(SourceFile:7)
	at androidx.activity.l.w(SourceFile:44)
	at c1.b1.a(SourceFile:75)
	at c1.b0$b.x(SourceFile:129)
	at c1.n.C0(SourceFile:127)
	at a1.s0$a.d(SourceFile:33)
	at c1.b0$b$b.B(SourceFile:20)
	at f0.h$a.a(SourceFile:64)
	at f0.b0.B(SourceFile:7)
	at androidx.activity.l.w(SourceFile:44)
	at c1.b1.a(SourceFile:75)
	at c1.b0$b.I0(SourceFile:65)
	at c1.b0$b.C0(SourceFile:48)
	at a1.s0$a.d(SourceFile:33)
	at k.e.b(SourceFile:46)
	at k.f$b.W(SourceFile:25)
	at a1.g0.e(SourceFile:40)
	at c1.b0$b$a.B(SourceFile:105)
	at f0.h$a.a(SourceFile:64)
	at f0.b0.B(SourceFile:7)
	at androidx.activity.l.w(SourceFile:44)
	at c1.b1.a(SourceFile:75)
	at c1.b0$b.x(SourceFile:129)
	at c1.n.C0(SourceFile:127)
	at a1.s0$a.h(SourceFile:53)
	at m0.k0$a.W(SourceFile:18)
	at a1.g0.e(SourceFile:40)
	at c1.t.C0(SourceFile:45)
	at a1.s0$a.f(SourceFile:75)
	at k.o$a.W(SourceFile:11)
	at a1.g0.e(SourceFile:40)
	at c1.t.C0(SourceFile:45)
	at a1.s0$a.i(SourceFile:37)
	at c1.b0$b$b.B(SourceFile:24)
	at f0.h$a.a(SourceFile:64)
	at f0.b0.B(SourceFile:7)
	at androidx.activity.l.w(SourceFile:44)
	at c1.b1.a(SourceFile:75)
	at c1.b0$b.I0(SourceFile:65)
	at c1.b0$b.C0(SourceFile:48)
	at a1.s0$a.g(SourceFile:78)
	at a1.w0$b.W(SourceFile:11)
	at a1.g0.e(SourceFile:40)
	at c1.b0$b$a.B(SourceFile:105)
	at f0.h$a.a(SourceFile:64)
	at f0.b0.B(SourceFile:7)
	at androidx.activity.l.w(SourceFile:44)
	at c1.b1.a(SourceFile:75)
	at c1.b0$b.x(SourceFile:129)
	at c1.n.C0(SourceFile:127)
	at a1.s0$a.d(SourceFile:33)
	at c1.b0$b$b.B(SourceFile:20)
	at f0.h$a.a(SourceFile:64)
	at f0.b0.B(SourceFile:7)
	at androidx.activity.l.w(SourceFile:44)
	at c1.b1.a(SourceFile:75)
	at c1.b0$b.I0(SourceFile:65)
	at c1.b0$b.C0(SourceFile:48)
	at a1.s0$a.f(SourceFile:75)
	at c1.h0.k(SourceFile:219)
	at c1.h0.g(SourceFile:69)
	at androidx.compose.ui.platform.AndroidComposeView.onLayout(Unknown Source:4)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at androidx.compose.ui.platform.a.e(Unknown Source:27)
	at androidx.compose.ui.platform.a.onLayout(Unknown Source:0)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:374)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:312)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:24461)
	at android.view.ViewGroup.layout(ViewGroup.java:7412)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:374)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:312)
```

**Comment by Bnyro** [comment]
Oh, it's obfuscated once again :/
I probably understand as much as you do here :)
I'm gonna send you a debug version later that doesn't obfuscate the logs!

**Comment by sheeepdev** [comment]
I opened the app by accident and saw that it didnt crash and its working normally...

**Comment by Bnyro** [comment]
Oh, damn, I totally forgot to send you a debug version of the app, sorry!
Did you recently update the app or delete its data or do anything else that could have impacted its behavior?

**Comment by sheeepdev** [comment]
> Oh, damn, I totally forgot to send you a debug version of the app, sorry! Did you recently update the app or delete its data or do anything else that could have impacted its behavior?

Well I tried clearing the data and updating like 10 times 3 days ago but besides that no

**Comment by Bnyro** [comment]
Hmm, weird.
I'll close the issue for now, if it happens again, feel free to open a new issue :)
