### ISSUE TITLE
App crashes when changing LibreTranslate instance

### ISSUE THREAD

**Issue by semka95** [Bnyro/TranslateYou#45]
### Steps to reproduce

1. Go to settings
2. Try to edit instance field

### Expected behavior

I should edit instance URL

### Actual behavior

App crashes

### Translate You version

1.5-1.6

### Android version

Android 10

### Other details

I tried 1.5 and 1.6 version of the app, same behavior.

https://user-images.githubusercontent.com/4162760/196023883-0d06e560-e62a-4fc4-8f37-6a7a81159cd8.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Thank you for reporting the issue, I'll make a new release including the fix soon!

**Comment by semka95** [comment]
Thank you!

**Comment by FabiRich** [comment]
Good evening,

I still got a crash, when I try to change the URL. I have recorded the process and the exception is underneath.

https://github.com/you-apps/TranslateYou/assets/76914324/c3bffaa6-e8ad-475f-91c6-13452322947b



java.lang.IllegalArgumentException: baseUrl must end in /: https://de.libretranslate.com/translate
	at q5.a1.a(SourceFile:58)
	at com.bnyro.translate.api.lt.LTEngine.createOrRecreate(SourceFile:17)
	at s3.h.a(SourceFile:19)
	at s3.h.h0(SourceFile:17)
	at l3.e0.h0(SourceFile:174)
	at g.x.h0(SourceFile:1659)
	at s.o.h0(SourceFile:313)
	at androidx.activity.result.g.d(Unknown Source:25)
	at g.x.h0(SourceFile:1237)
	at p1.z.b(SourceFile:32)
	at p1.z.endBatchEdit(Unknown Source:0)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:477)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:89)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
