### ISSUE TITLE
keep crashing

### ISSUE THREAD

**Issue by Haidarah-Esmander** [Bnyro/TranslateYou#57]
### Steps to reproduce

it crashes when i try to enter a word to translate

### Expected behavior

it should work as expected

### Actual behavior

the application crashes when I try to translate any word 

### Translate You version

2.0

### Android version

android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Ilithy** [comment]
Yes indeed, I also observe this behavior, but only when I select Deepl or MyMemory as translation engine (no matter what options are checked, with or without simultaneous translation, history etc...)


Here are some logs recovered during TY crashes, depending on the translation engine:

**with deepl selected:**

```

FATAL EXCEPTION: DefaultDispatcher-worker-8
Process: com.bnyro.translate.nf, PID: 30551
v5.j: HTTP 400 
	at v5.o.b(SourceFile:140)
	at v5.t$a.b(Unknown Source:10)
	at k5.x$a.a(SourceFile:22)
	at l5.b.run(Unknown Source:17)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: c5.h0: [p1{Cancelling}@5ac619d, Dispatchers.IO]

	```

	**with mymemory:**

	```

	FATAL EXCEPTION: DefaultDispatcher-worker-2
Process: com.bnyro.translate.nf, PID: 30941
x3.f: Cannot construct instance of `java.util.ArrayList` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('')
 at [Source: (k5.d0$a); line: 1, column: 506] (through reference chain: com.bnyro.translate.api.mm.obj.MMTranslationResponse["matches"])
	at r3.f.R(SourceFile:12)
	at r3.f.y(SourceFile:82)
	at u3.w.a(SourceFile:69)
	at u3.w.q(Unknown Source:0)
	at w3.f.d(Unknown Source:37)
	at v3.i.j(Unknown Source:26)
	at u3.c.y0(Unknown Source:30)
	at u3.c.d(SourceFile:14)
	at r3.r.d(SourceFile:95)
	at q0.d.a(SourceFile:39)
	at v5.t.d(SourceFile:59)
	at v5.t$a.b(Unknown Source:2)
	at k5.x$a.a(SourceFile:22)
	at l5.b.run(Unknown Source:17)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: c5.h0: [p1{Cancelling}@8f310fc, Dispatchers.IO]

```

I don't know if it will be useful...
Thanks

**Comment by Bnyro** [comment]
Oh, damn, I forgot to change back some code I used for testing, I'll quickly fix that and update a new release later thanks for the call!
